[versions]
agp = "8.13.2"
kotlin = "2.3.0"
kotlin-dsl = "6.5.2"
compose-plugin = "1.9.3"
androidx-activityCompose = "1.12.2"
datastore = "1.2.0"
koin = "4.1.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }

#Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinDsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin-dsl" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
